[tool.poetry]
name = "pixiv-bot"
version = "1.0.3"
description = "pixiv-bot"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
nonebot2 = "^2.0.0.a16"
nb-cli = "^0.5.1"
PixivPy-Async = "^1.2.13"
aiohttp-socks = "^0.6.0"
Pillow = "^8.4.0"
nonebot_plugin_apscheduler = "^0.1.2"
nonebot-adapter-cqhttp = "^2.0.0a16"
motor = "^2.5.1"

[tool.poetry.dev-dependencies]
nonebot-test = "^0.1.0"

[nonebot.plugins]
plugin_dirs = ["src/plugins"]
plugins = ["nonebot_plugin_apscheduler"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
