[tool.poetry]
name = "mirai-pixiv-bot"
version = "0.2.1"
description = ""
authors = ["ssttkkl <huang.wen.long@hotmail.com>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6"
PixivPy = "^3.5.10"
json5 = "^0.9.5"
Pillow = "^8.1.0"
aiofiles = "^0.6.0"
loguru = "^0.5.3"
graia-application-mirai = "^0.15.0"
graia-template = "^0.0.4"
sortedcontainers = "^2.3.0"
devtools = "^0.6.1"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[[tool.poetry.source]]
name = "douban"
url = "https://pypi.doubanio.com/simple/"